replace select with angular material tree
openMF/web-app pull request #1235
Opened 2020-08-29 09:01 UTC by zerefwayne

## Description

#### Part 1: Convert the office list into a hierarchical object structure using office.hierarchy string.

I used a method similar to how a trie data structure is created to generate an object as specified in the documentation.

#### Part 2: Reading the Angular Material Checkbox Tree guidelines and sample code.

I went through the link given in description of the issue to understand how Angular Material Tree works.

#### Part 3: Integrating the specified code sections into CreateHoliday component and remove the previous select box.

I removed the select option and added all the required codes.

#### Part 4: Updating offices in HolidayForm object similar to what was being done before.

The format of checkListSelection Angular module is different from what we require, i.e. a simple list of strings (office ids). Therefore I create a function that updates the HolidayForm whenever checklist changes.

## Related issues and discussion
#1231 

## Screenshots, if any

The list generated by the Angular Material Tree comes in the console and I have tested it thoroughly.

![image](https://user-images.githubusercontent.com/28949397/91633120-62b43480-ea03-11ea-8da6-d085fff1a3f2.png)

## Checklist

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

2020-09-01 12:38 UTC, karantakalkar requested changes
Hi @zerefwayne good effort some changes in functionality are needed:

Node tree on dev instance https://dev.mifos.io/#/createholiday is as follows:
![Screenshot from 2020-09-01 18-00-14](https://user-images.githubusercontent.com/54709463/91851660-34418e00-ec7d-11ea-9aab-e6ba239681ba.png)

You need to check construction of first node, all peer nodes of Head Office (as in this screenshot) should be it's children.
![Screenshot from 2020-09-01 18-00-00](https://user-images.githubusercontent.com/54709463/91851662-36a3e800-ec7d-11ea-94a5-0d8759b7bcad.png)

In case you want to test it with different data change baseApiUrl in `environment.ts` to staging.mifos.io or demo.mifos.io (but login using dev.mifos.io only as auth on older servers is different). you can also check the respective community app (older interface)  functionality by visiting these urls.

2020-09-01 16:47 UTC, zerefwayne commented
@karantakalkar I somehow completely missed the root office condition. Thank you for pointing that out. I've fixed it, please have a look.

![image](https://user-images.githubusercontent.com/28949397/91882673-f35b7080-eca0-11ea-86c2-ee6dfc9c5682.png)

2020-09-01 17:22 UTC, karantakalkar requested changes
You can test the API responses on community app instances, it may give off errors but at least request payload and error code should be the same for same input.

Currently we are submitting an array, which is giving of 500.

![Screenshot from 2020-09-01 22-44-23](https://user-images.githubusercontent.com/54709463/91885416-5cdd7e00-eca5-11ea-9632-a2bc9401a763.png)


In community app API request there is an object array, so you need to map the offices array to become this:
![Screenshot from 2020-09-01 22-44-11](https://user-images.githubusercontent.com/54709463/91885084-cc06a280-eca4-11ea-805d-77b0b6cff07c.png)

2020-09-01 17:22 UTC, karantakalkar commented on angular.json
>              ],
exclude this file from your commit

2021-01-07 16:16 UTC, karantakalkar commented
Closing due to inactivity.

2021-01-07 16:16 UTC, closed without merging