fix(sidenav.component.scss): Hover cursor over Logo changes to hand-cursor after expanding Sidenav
openMF/web-app pull request #1242
Opened 2020-09-15 12:41 UTC by shobhi1310

App Brand on hover now shows hand-pointer, earlier showed simple cursor-type.

Fixes: #746

## Description
Describe the changes made and why they were made instead of how they were made. List any dependencies that are required for this change.

## Related issues and discussion
#746 

## Screenshots, if any
![image](https://user-images.githubusercontent.com/42507632/93211414-d5047300-f77e-11ea-8e25-0fa3085ff259.png)

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

2020-09-17 09:18 UTC, karantakalkar requested changes

2020-09-17 09:18 UTC, karantakalkar commented on src/app/core/shell/sidenav/sidenav.component.scss
> +    cursor: pointer;
keep it below `color: #444` line.
```suggestion
 &:hover {
     cursor: pointer;
 }
```

2020-09-17 12:21 UTC, karantakalkar commented
squash your commits into a single commit

2020-09-17 13:33 UTC, shobhi1310 commented
![image](https://user-images.githubusercontent.com/42507632/93477252-6bb86780-f918-11ea-81b0-c12a6bbb253c.png)

How to overcome this merge branch commit ?

2020-09-20 13:41 UTC, shobhi1310 commented
I am closing my pull request for this case, because of some error which I did in the commit tree, I will be creating a new PR

2020-09-20 13:41 UTC, closed without merging