Changed routes
openMF/web-app pull request #1243
Opened 2020-09-15 19:23 UTC by Abhirup-99

## Description
Changing route names to bring about parity.

## Related issues and discussion
#774 

## Screenshots, if any

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

2020-09-17 08:08 UTC, karantakalkar requested changes
Change all `view/:id` routes similarly in this file, also please follow commit message guidelines.

2020-09-17 16:54 UTC, Abhirup-99 commented
@karantakalkar please review. 
**Note**: I have changed position of 1 route to ensure it doesn't bother any other routes.

2020-09-18 06:01 UTC, karantakalkar requested changes
you will need to change routing of all buttons where these routes are accessible from `view/:id` to `:id`, test data can be found on demo.mifos.io, you can change server in environment.ts. 
Please test routing of all changed pages before requesting review.

2020-09-18 10:22 UTC, Abhirup-99 commented
@karantakalkar do talk a look now. It seems ready for review.

2020-09-21 15:07 UTC, Abhirup-99 commented
@karantakalkar can you take a look into this? I think it's ready for review now.

2020-09-24 07:18 UTC, karantakalkar requested changes
are you sure you have checked all buttons/mat table rows for routing changes? and tested each route change?

2020-09-24 07:18 UTC, karantakalkar commented on src/app/accounting/chart-of-accounts/create-gl-account/create-gl-account.component.ts
> +      this.router.navigate([`${response.resourceId}`], { relativeTo: this.route });
```suggestion
      this.router.navigate([response.resourceId], { relativeTo: this.route });
```

2020-09-24 08:21 UTC, Abhirup-99 commented
@karantakalkar every route has been checked thoroughly.

2020-09-25 10:17 UTC, Abhirup-99 commented
@karantakalkar your changes are incoporated.

2020-10-17 02:14 UTC, Abhirup-99 commented
@karantakalkar can you review this pr, it's sitting here for a long time.

2022-11-02 01:13 UTC, closed without merging