feat: Removed css to ensure darker themes have a lighter logo.
openMF/web-app pull request #1246
Opened 2020-09-21 17:58 UTC by Abhirup-99

## Description
Removed css to ensure darker themes have a light logo.

## Related issues and discussion
Fixes #747

## Screenshots, if any
![Screenshot from 2020-09-21 23-27-05](https://user-images.githubusercontent.com/48902681/93803179-18208380-fc62-11ea-8b39-4556c3a18ee6.png)

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

2020-09-21 17:59 UTC, Abhirup-99 commented
@karantakalkar do take a look, it is ready for review.

2020-09-24 07:13 UTC, karantakalkar requested changes
Also fix the color of username and profile/settings icons just below it, attach 2 screenshots one in light and one in dark background.

2020-09-24 08:22 UTC, Abhirup-99 commented
Ok sure.

2020-09-24 11:35 UTC, Abhirup-99 commented
Profile icon is an image, do you want me to add another one when the theme is changed?

2020-09-24 12:25 UTC, Abhirup-99 commented
![Screenshot from 2020-09-24 17-51-57](https://user-images.githubusercontent.com/48902681/94144640-0bcd3e00-fe8f-11ea-8d4a-070867761168.png)
![Screenshot from 2020-09-24 17-51-42](https://user-images.githubusercontent.com/48902681/94144648-0d970180-fe8f-11ea-9697-88d0710e288d.png)

2020-09-24 12:25 UTC, Abhirup-99 commented
@karantakalkar the updated images

2020-09-25 05:00 UTC, karantakalkar commented on src/app/core/shell/sidenav/sidenav.component.html
> -        <img src="assets/images/user_placeholder.png" alt="app-user-photo">
undo this, restore profile image and related changes, upload feature is going to be added later, that's why i didn't ask you to change color of image.

2020-09-25 08:07 UTC, Abhirup-99 commented
![Screenshot from 2020-09-25 13-30-13](https://user-images.githubusercontent.com/48902681/94242831-3c1ae800-ff34-11ea-823c-9a36aefad3ae.png)
![Screenshot from 2020-09-25 13-30-03](https://user-images.githubusercontent.com/48902681/94242842-3e7d4200-ff34-11ea-907d-4c45ba8a70e9.png)

2020-09-25 08:07 UTC, Abhirup-99 commented
@karantakalkar final changes.

2020-09-25 09:18 UTC, karantakalkar approved these changes
Thanks!

2020-09-25 09:20 UTC, merged

2020-09-25 09:23 UTC, Abhirup-99 commented
> Thanks!

@karantakalkar Thanks a lot for merging, this is my first meaningful pr in open source to be merged.