feat: Create view survey page for respective surveys in systems section of admin.
openMF/web-app pull request #1247
Opened 2020-09-25 11:16 UTC by shobhi1310

A new section named view-survey added under manage-surveys with necessary changes to view individual questionnaires of each survey in a new page.

## Description
View Survey page visible.
Table made and suitable styling added
Survey heading added to the top section

## Related issues and discussion
Fixes: #580

## Screenshots, if any
![image](https://user-images.githubusercontent.com/42507632/94260809-6f6a7080-ff4e-11ea-96c0-8929ec1f4f5a.png)

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

2020-09-26 02:53 UTC, spider0061 commented
@shobhi1310 Travis test are failing because of linting errors. You can remove linting errors by using ng lint --fix=true . Although you may have to remove some errors manually but it will fix most of the errors and will tell you where are other errors present.

2020-10-03 15:41 UTC, shobhi1310 commented
@karantakalkar 
Please do review my PR once.

2020-10-07 10:34 UTC, karantakalkar requested changes
On surface it looks fine, can you please format the code, I'll review the functionality once more in a while

2020-10-07 10:34 UTC, karantakalkar commented on src/app/system/manage-surveys/survey.resolver.ts
> + * Report data resolver.
Appropriate comments please

2020-10-07 10:34 UTC, karantakalkar commented on src/app/system/manage-surveys/view-survey/view-survey.component.html
> +            <div fxFlex="40%" fxFlex.lt-md="50%" class="header">
we use 2 spaces as indent

2020-10-07 10:34 UTC, karantakalkar commented on src/app/system/manage-surveys/view-survey/view-survey.component.html
> +                    <mat-card-content>
please refactor for indents

2020-10-07 10:34 UTC, karantakalkar commented on src/app/system/manage-surveys/view-survey/view-survey.component.scss
> +}
new line at eof

2020-10-07 10:34 UTC, karantakalkar commented on src/app/system/manage-surveys/view-survey/view-survey.component.ts
> +
spacing, comments and indents, see accounting section

2020-10-16 15:38 UTC, karantakalkar approved these changes
Good work, some minor code and design changes might be needed however they can be incorporated along with edit survey page.

2020-10-16 15:39 UTC, merged

2020-10-16 16:09 UTC, shobhi1310 commented
ohh ok thanks