Feat: Create dialog for users to add/remove custom servers
openMF/web-app pull request #1284
Opened 2020-12-26 11:40 UTC by sankha555

Feat: Create dialog for users to add/remove custom servers

## Description
Created a new dialog component "Custom Server Component" under Server Selector component to add custom servers to a table and display the table in the dialog box. Added servers can also be deleted from the table. Selected servers in the table are added to the list of mifosXServers in localstorage using the settings service. This will help users to add and store custom servers to run the web app.

## Related issues and discussion
Fixes #1273 

## Screenshots
New custom server dialog box
![Screenshot 2020-12-26 at 4 30 06 PM](https://user-images.githubusercontent.com/54751139/103150730-b14cc200-479c-11eb-97e5-a170c0ad516d.png)

Added a new custom dummy server "https://mifos.xoxo" to the custom servers table
![Screenshot 2020-12-26 at 4 30 34 PM](https://user-images.githubusercontent.com/54751139/103150763-13a5c280-479d-11eb-8fdc-67fe24825736.png)

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

2020-12-26 12:59 UTC, BLasan commented on src/app/shared/server-selector/custom-server/custom-server.component.html
> +</div>
Add a new line

2020-12-26 12:59 UTC, BLasan commented on src/app/shared/server-selector/custom-server/custom-server.component.scss
> +}
Add a new line

2020-12-26 13:01 UTC, BLasan commented on src/app/shared/server-selector/custom-server/custom-server.component.ts
> +import { Component, OnInit, Inject } from '@angular/core';
Add the required comment above angular imports

2020-12-26 13:02 UTC, BLasan commented on src/app/shared/server-selector/custom-server/custom-server.component.ts
> +}
Add a new line at the EOF

2020-12-26 13:05 UTC, BLasan requested changes
Please make the required changes. Add a new line at each and every EOF. Looks good for me!

2020-12-26 14:04 UTC, sankha555 commented
@BLasan Made the required changes. Please review. Thanks!

2020-12-27 05:57 UTC, BLasan commented on src/app/shared/server-selector/custom-server/custom-server.component.html
> +</div>
There should be a new line after 48th

2020-12-27 05:59 UTC, BLasan requested changes
@sankha555 Add an empty line at the end of the code. This empty line must be presented in all ts,html and scss files

2020-12-27 06:08 UTC, sankha555 commented
> @sankha555 Add an empty line at the end of the code. This empty line must be presented in all ts,html and scss files

@BLasan I think I had already added the required newlines to all the files in commit 67797f02ddb60b1f10824d8b38b2eb5564ab29e6 in response to the changes suggested by you yesterday. Please take a look at it

2020-12-27 07:11 UTC, BLasan commented
> > @sankha555 Add an empty line at the end of the code. This empty line must be presented in all ts,html and scss files
> 
> @BLasan I think I had already added the required newlines to all the files in commit [67797f0](https://github.com/openMF/web-app/commit/67797f02ddb60b1f10824d8b38b2eb5564ab29e6) in response to the changes suggested by you yesterday. Please take a look at it

Thanks. We have to wait until Karan review and approve this PR

2020-12-27 08:40 UTC, sankha555 commented
Thanks @BLasan ! @karantakalkar kindly take a look if you find time and provide your feedback about the utility of the PR and possible merging of the PR. It would be really helpful for me in future contributions. Thanks in advance!

2020-12-29 14:31 UTC, karantakalkar commented
LGTM, but we will need to wait till travis builds are back.

2020-12-29 15:44 UTC, Abhirup-99 commented
> LGTM, but we will need to wait till travis builds are back.

Travis builds are now migrated to one time free plan of 10k credits aka 1k Linux builds only. After this, you have to move to one of the paid plans. It would be better if you move to Github Actions.
I would be happy to push a pr, just did it for my company.

2021-01-09 10:58 UTC, Abhirup-99 commented
1 commit per pr, please squash them.

2021-01-09 11:42 UTC, BLasan commented
> @BLasan Made the required changes. Please review. Thanks!

shall we squash the commits and rename the commit message as **feat: Create dialog for users to add/remove custom servers**

2021-02-27 11:52 UTC, apurv-1 approved these changes

2022-10-02 01:21 UTC, closed without merging