Added tooltip text for the sidenav component
openMF/web-app pull request #1290
Opened 2021-01-06 20:04 UTC by abhishekkumar08

## Description
Added tooltip for the following icons:-
- Dashboard
- Navigation
- Checker Inbox and Tasks
- Individual Collection Sheets
- Notifications
- Frequent Postings
- Create Journal Entry
- Chart Of Accounts
- Keyboard Shortcuts
- Help
- Search

## Related issues and discussion
#1289 

## Screenshots, if any
![image](https://user-images.githubusercontent.com/59651136/103814748-3b900280-5088-11eb-8a54-2b42d4fa1821.png)
![image](https://user-images.githubusercontent.com/59651136/103814766-40ed4d00-5088-11eb-9d32-4b301f234a03.png)

## NOTE
I have added the tooltip text in the block of the icons, if you want the tooltip only to appear when the cursor moves on to the icon, then you can tell me I can make changes according to that.

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

2021-01-07 15:50 UTC, karantakalkar requested changes
Thanks for the contribution!, please follow commit message and PR template guidelines.

2021-01-07 17:45 UTC, abhishekkumar08 commented
@karantakalkar Please review the PR, done the requested changes.

2021-01-08 08:32 UTC, karantakalkar approved these changes

2021-01-09 07:57 UTC, sankha555 commented
@karantakalkar @abhishekkumar08 We can add a tooltip for the the notifications and color change icons too, what do you think about it? If that's required, I can make a patch for that. Thanks!

2021-01-09 08:01 UTC, abhishekkumar08 commented
@sankha555 they are already there.

2021-01-09 08:02 UTC, sankha555 commented
> @sankha555 they are already there.

Ohh I see, no worries in that case then :)

2021-05-22 11:44 UTC, merged