refractor: update dateformats and language
openMF/web-app pull request #1292
Opened 2021-01-07 22:33 UTC by abhishekkumar08

## Description
Update dateformats and language with centralized data in products
module

## Related issues and discussion
#1213 

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

2021-01-09 12:01 UTC, BLasan commented
@abhishekkumar08 Shall we rename the commit message as **refactor: update dateformats and language with centralized data in products module** . No need of two lines for a commit message in here

2021-01-09 12:08 UTC, abhishekkumar08 commented
@BLasan okay would do that. Thanks!

2021-01-16 17:56 UTC, BLasan commented on src/app/products/charges/create-charge/create-charge.component.ts
> +    private productsService: ProductsService,
Make vertical alignments of variables consistent to line 49 variable.

2021-01-16 17:58 UTC, BLasan commented on src/app/products/charges/edit-charge/edit-charge.component.ts
>      private productsService: ProductsService,
Make proper vertical alignment as in other components

2021-01-16 17:58 UTC, BLasan commented on src/app/products/fixed-deposit-products/create-fixed-deposit-product/create-fixed-deposit-product.component.ts
> +    private productsService: ProductsService,
vertical alignment of variables

2021-01-16 18:00 UTC, BLasan commented on src/app/products/fixed-deposit-products/edit-fixed-deposit-product/edit-fixed-deposit-product.component.ts
> +  /**
Add params for other variables declared within constructor

2021-01-16 18:05 UTC, BLasan commented on src/app/products/floating-rates/edit-floating-rate/edit-floating-rate.component.ts
> +    private formBuilder: FormBuilder,
Consider vertical alignment as mentioned above. This should be applicable for all the components you have modified.

2021-01-16 18:06 UTC, BLasan commented on src/app/products/products.service.ts
> +    const httpParams = new HttpParams().set('dateFormat', this.settingsService.dateFormat)
Consider the alignments

2021-01-16 18:08 UTC, BLasan requested changes
@abhishekkumar08 Please make the requested changes

2021-01-17 05:52 UTC, abhishekkumar08 commented
@BLasan Thanks for the review would do that.

2021-01-17 17:08 UTC, abhishekkumar08 commented
@BLasan Please check if everything is in place. Should I squash the commits into one?

2021-01-17 17:23 UTC, BLasan commented
> @BLasan Please check if everything is in place. Should I squash the commits into one or is it ok?

You need to squash the commits

2021-01-17 17:26 UTC, abhishekkumar08 commented
> 
> 
> > @BLasan Please check if everything is in place. Should I squash the commits into one or is it ok?
> 
> You need to squash the commits

Okay on that! Also everything's in place? Thanks for the review.

2021-01-17 17:37 UTC, BLasan commented
> > > @BLasan Please check if everything is in place. Should I squash the commits into one or is it ok?
> > 
> > 
> > You need to squash the commits
> 
> Okay on that! Also everything's in place? Thanks for the review.

Will check :)

2021-01-17 17:41 UTC, BLasan commented on src/app/products/charges/edit-charge/edit-charge.component.ts
>    ) {
move these parentheses to line no 60

2021-01-17 17:46 UTC, BLasan commented on src/app/products/fixed-deposit-products/create-fixed-deposit-product/create-fixed-deposit-product.component.ts
>  import { FixedDepositProductAccountingStepComponent } from '../fixed-deposit-product-stepper/fixed-deposit-product-accounting-step/fixed-deposit-product-accounting-step.component';
Shall we add headers(comments) for the imports?  You can get an idea by looking at edit-charge.component.ts file

2021-01-17 17:46 UTC, abhishekkumar08 commented
@BLasan okay, review all the code I will update the changes at last. @karantakalkar Please review this PR. Thanks.

2021-01-17 17:49 UTC, BLasan commented on src/app/products/share-products/share-product-stepper/share-product-market-price-step/share-product-market-price-step.component.ts
>    displayedColumns: string[] = ['fromDate', 'shareValue', 'actions'];
add the description for the variable

2021-01-17 17:52 UTC, BLasan requested changes
@abhishekkumar08 Nice work! Please make the required changes

2021-01-17 17:56 UTC, BLasan commented
@abhishekkumar08 Please close the outdated requests

2021-01-17 17:58 UTC, abhishekkumar08 commented
> 
> 
> @abhishekkumar08 Please close the outdated requests

Didn't get that? @BLasan

2021-01-17 18:07 UTC, BLasan commented
> > @abhishekkumar08 Please close the outdated reviews
> 
> Didn't get that? @BLasan

Outdated conversations regarding to the review.
![Screenshot from 2021-01-17 23-35-12](https://user-images.githubusercontent.com/43112139/104851766-fb990d00-591c-11eb-8afd-994df839e9fa.png)

2021-01-19 17:53 UTC, abhishekkumar08 commented
@karantakalkar Please review this PR. Thanks.

2021-08-08 07:58 UTC, Jov03 approved these changes

2021-08-08 07:58 UTC, merged