Allow accounting mappings for fund source asset or liability
openMF/web-app pull request #1493
Opened 2022-08-01 22:28 UTC by josehernandezfintecheandomx

## Description

There are a couple of Loan product GL mapping changes for Loan products:

Support Fund source GL Account as Asset or Liability type,

Add the Goodwill credit as Expense GL account type for all the Accounting types used, Cash, Accrual Upfront or Accrual Periodic

## Screenshots, if any
<img width="1227" alt="Screen Shot 2022-08-01 at 13 34 39" src="https://user-images.githubusercontent.com/44206706/182256162-0bda0f36-b8fb-4ca0-8cb2-14b15f27a844.png">

<img width="1227" alt="Screen Shot 2022-08-01 at 14 01 13" src="https://user-images.githubusercontent.com/44206706/182256181-18983570-77c9-4f85-909b-c416286e8917.png">

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

2022-08-03 13:57 UTC, galovics requested changes

2022-08-03 13:57 UTC, galovics commented on src/app/accounting/chart-of-accounts/gl-account-tree.service.ts
> +          console.log(glAccount);
Please remove the console log. Thanks.

2022-08-03 15:33 UTC, josehernandezfintecheandomx commented on src/app/accounting/chart-of-accounts/gl-account-tree.service.ts
> +          console.log(glAccount);
Done!

2022-08-04 13:57 UTC, galovics approved these changes
LGTM

2022-08-04 13:57 UTC, merged