Added ToolTips in Fixed Deposit Products
openMF/web-app pull request #1677
Opened 2023-02-02 20:42 UTC by PC-11-00

## Description
Added ToolTips in Fixed Deposit Products that provided a valuable aid to understanding functionality of the system .

## Related issues and discussion
#1654 

## Screenshots, if any

https://user-images.githubusercontent.com/76156941/216444727-a2f262f5-ea48-472f-a63b-d882357f1875.mov

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

2023-02-05 16:51 UTC, rish106 commented
Can you squash the commits into a single one and follow the [commit message conventions](https://github.com/openMF/web-app/blob/master/.github/COMMIT_MESSAGE.md)?

2023-02-07 18:06 UTC, PC-11-00 commented
@rish106 @spider0061 have a look

2023-02-07 20:26 UTC, rish106 requested changes
Kindly make these changes and also change the title of this pull request to the same as commit message

2023-02-07 20:26 UTC, rish106 commented on src/app/products/fixed-deposit-products/fixed-deposit-product-stepper/fixed-deposit-product-interest-rate-chart-step/fixed-deposit-product-interest-rate-chart-step.component.ts
> +import {TooltipPosition} from '@angular/material/tooltip';
```suggestion
import { TooltipPosition } from '@angular/material/tooltip';
```

2023-02-07 20:26 UTC, rish106 commented on src/app/products/fixed-deposit-products/fixed-deposit-product-stepper/fixed-deposit-product-settings-step/fixed-deposit-product-settings-step.component.ts
> +import {TooltipPosition} from '@angular/material/tooltip';
```suggestion
import { TooltipPosition } from '@angular/material/tooltip';
```

2023-02-07 20:26 UTC, rish106 commented on src/app/products/fixed-deposit-products/fixed-deposit-product-stepper/fixed-deposit-product-terms-step/fixed-deposit-product-terms-step.component.ts
> +import {TooltipPosition} from '@angular/material/tooltip';
```suggestion
import { TooltipPosition } from '@angular/material/tooltip';
```

2023-02-08 04:33 UTC, PC-11-00 commented
@rish106 have a look, I changed the name of the PR which matches with the commit, and also made the suggested changes

2023-02-08 04:46 UTC, spider0061 commented
LGTM!

2023-02-08 09:55 UTC, merged